### ISSUE TITLE
Police 1.3 broken and not working

### ISSUE THREAD

**Issue by Valkatastz** [ESX-Org/esx_policejob#199]
@ElPumpo I don't know how you are screwing stuff in these codes and what is your logic but please, be a little bit more cautions and logical. Firstly, you broke up with esx_ambulancejob and it's not working with the latest updates.

 Now, esx_policejob with version 1.3 and weashops are not working either. The police either the cloakroom or the police menu are not opening when you press the related buttons (F6) and when you enter in the zone for cloakroom. In the code you have overlay it multiple times and it returns "nil" values where "showhelpnotification" is broken af. It always returns nil (0) value and on F8 console it says "error nil value is not acceptable for ShowHelpNotification" when I enter in the cloakroom zone or press F6. I checked your code, you have set it up to open the cloakroom by "E" but in same time you are redirecting it multiple times to a nil value. 

Can you be that nice and fix your logic and ambulancejob as well as policejob and stop messing with it anymore? That would be highly appreciate it if you can fix your logic!

**Comment by ElPumpo** [comment]
> Firstly, you broke up with esx_ambulancejob and it's not working with the latest updates.

> Can you be that nice and fix your logic and ambulancejob as well as policejob and stop messing with it anymore? That would be highly appreciate it if you can fix your logic!

Why do you keep using arguments like that when reporting an issue? Do you want to get banned? because It'll be quick. Final warning from me.

Now to the accual problem, if you have problems with `ShowHelpNotification` being `nil`, or something similar it's a hint that you're running an old version of esx. Have you downgraded?
With the latest version of ESX you should have a  `ShowHelpNotification()` function on `client/functions.lua`, at line 60. I know you downgraded in a comment on ambulancejob, I've fixed the bug with math objects missing, I had forgot to commit the new resource manifest which is also why I couldn't reproduce the problem.

Fact is that the resources evolve, if you update policejob you also have to update its dependencies (not always true). If you don't want improved resources simply don't update and stick to one version that works.
