### ISSUE TITLE
Cant check ID

### ISSUE THREAD

**Issue by ghost** [ESX-Org/esx_policejob#230]
F6 menu ID check wont work unless they player have weapon license or driver license.

And any way to make custom bills instead of that system that are made?

**Comment by LuffyCosta** [comment]
Just do, as i did on my configs for now, create a license that everybody has. In the licenses table create a civil type, then in the ESX identity on the setIdentity function add a mysql async task to insert into the user licenses with the steam id and the civil licence. This way every user has a license ;) hope i could help

**Comment by LuffyCosta** [comment]
Sorry for the late reply. But what you have to do is:

1- Create a row in the licenses table, like a civil registry or something that you want
2- Go to your esx_identity/Server/Main.lua and alter the query where it creates a character and user. Now you have to add a new query to add the created license above to the user_licences table. 

Pls dont forget to do this after all the other 2 queries are done so that you don't have errors in your DB

Hope i could help this time :)

**Comment by HytroN** [comment]
Can you show how it looks like? Im not good at this, but I'm looking forward to getting better. I already made a Civil Passport license in Mysql/PHP. Thanks for helping!

**Comment by Patrickstek121** [comment]
same issue

**Comment by lvp11** [comment]
same issue

**Comment by lvp11** [comment]
Any fixes?
