### ISSUE TITLE
Open police job menu in vehicles?

### ISSUE THREAD

**Issue by dmaskell92** [ESX-Org/esx_policejob#348]
How would I open the police job menu from inside a vehicle?

**Comment by dmaskell92** [comment]
The menu works fine in regular vehicles it seems, only when I'm sitting in a police vehicle the f6 menu won't open.

**Comment by HumanTree92** [comment]
Have u tried changing the key from f6. Set it to like page up or page down.

**Comment by peppinoita** [comment]
Sorry guys.
I have the same issue. the menu doesn't open only when in a police vehicle. Can you point me in the right direction to fix this? Did anyone experienced something similar? I am pretty sure there is no key conflict (also because I have 3 menu F5, F6 and F7 and none of that opens when in police vehicle).
Thank you for your reply.
