### ISSUE TITLE
Spawn vehicles insted of buy any 

### ISSUE THREAD

**Issue by osdeibi** [ESX-Org/esx_policejob#380]
its possible to add the old option to spawn vehicles instead of buy any vehicle?

**Comment by Cactusje** [comment]
Hi there, if I get you right, you want to use the old system (open the menu, displays the cars & click them to spawn + a vehicle deleter behind the garage doors OR option in the menu)

I can help you with this, but the code for it might not be 100% efficient. I also spent some time to get this done since in real life the government also pays for these things and not the police who is driving them 

Let me know
