### ISSUE TITLE
Not authorized

### ISSUE THREAD

**Issue by OwnaDash** [ESX-Org/esx_policejob#428]
When i try to access the "Vehicle Shop" it says "You're not authorized to buy this kind of vehicles."
No errors in console.
Can someone help me please?

**Comment by OwnaDash** [comment]
Switched to a version from a Fork

**Comment by Maczofficial** [comment]
OwnaDash How did you fix this

**Comment by badchulo** [comment]
@Maczofficial that's because Boss vehicles is empty in the config. Add one vehicle or change grade you will see how it's working

![imagen](https://user-images.githubusercontent.com/19668212/80863453-bd6b9880-8c7c-11ea-91fe-987d968cd258.png)

![imagen](https://user-images.githubusercontent.com/19668212/80863459-cc524b00-8c7c-11ea-955d-4093d70c678f.png)

**Comment by EpsilonCommunity** [comment]
> @Maczofficial that's because Boss vehicles is empty in the config. Add one vehicle or change grade you will see how it's working
> 
> ![imagen](https://user-images.githubusercontent.com/19668212/80863453-bd6b9880-8c7c-11ea-91fe-987d968cd258.png)
> 
> ![imagen](https://user-images.githubusercontent.com/19668212/80863459-cc524b00-8c7c-11ea-955d-4093d70c678f.png)

Where's the config file?

**Comment by Ianh5642** [comment]
I've added vehicle to every rank and tried every rank still says not authorized. Any ideas?
